version: "0.2"
ignorePaths:
  - .gitignore
  - pnpm-lock.yaml
  - mvnw
  - mvnw.cmd
dictionaryDefinitions: []
dictionaries: []
words:
  - classfile
  - classloaders
  - CLOB
  - codehaus
  - deployables
  - Dlvq
  - Dskip
  - errorlevel
  - fileset
  - filesets
  - FREEPDB
  - Gson
  - gvenzl
  - healthcheck
  - hikari
  - initdb
  - jayway
  - Jstl
  - NEXTVAL
  - NOCACHE
  - NOCYCLE
  - ojdbc
  - oradata
  - Pjetty
  - Plinux
  - Ptomcat
  - regdate
  - replycnt
  - replydate
  - replyer
  - rttr
  - SETLOCAL
  - Smails
  - SQLCODE
  - SQLERROR
  - sqlplus
  - SYSTIMESTAMP
  - TABLESPACE
  - taglibs
  - temurin
  - Thumbnailator
  - typehandler
  - updatedate
  - uploadpath
  - usebackq
  - userpw
  - VARCHAR
  - webapps
ignoreWords: []
import: []
